### ISSUE TITLE
Failed to make

### ISSUE THREAD

**Issue by mediumraresteak0** [pohlrabi404/Hyprfoci#11]
I ran make all in the cloned repo and got this:
```
g++ -shared -fPIC --no-gnu-unique main.cpp CDotDecoration.cpp -o hyprfoci.so -g `pkg-config --cflags pixman-1 libdrm hyprland pangocairo libinput libudev wayland-server xkbcommon` -std=c++2b -O2
In file included from main.cpp:1:
CDotDecoration.hpp:21:27: error: ‘SCallbackInfo’ has not been declared
   21 |   virtual void onKeypress(SCallbackInfo &info, std::any data);
      |                           ^~~~~~~~~~~~~
CDotDecoration.hpp:25:6: error: ‘HOOK_CALLBACK_FN’ was not declared in this scope
   25 |   SP<HOOK_CALLBACK_FN> m_pKeypressCallback;
      |      ^~~~~~~~~~~~~~~~
CDotDecoration.hpp:25:22: error: template argument 1 is invalid
   25 |   SP<HOOK_CALLBACK_FN> m_pKeypressCallback;
      |                      ^
CDotDecoration.hpp:27:6: error: ‘CTexture’ was not declared in this scope
   27 |   SP<CTexture> m_pTexture;
      |      ^~~~~~~~
CDotDecoration.hpp:27:14: error: template argument 1 is invalid
   27 |   SP<CTexture> m_pTexture;
      |              ^
In file included from main.cpp:3:
globals.hpp:32:43: error: ‘CTexture’ was not declared in this scope
   32 | inline std::unordered_map<std::string, SP<CTexture>> g_pTextures = {
      |                                           ^~~~~~~~
globals.hpp:32:43: error: template argument 1 is invalid
globals.hpp:32:51: error: template argument 2 is invalid
   32 | inline std::unordered_map<std::string, SP<CTexture>> g_pTextures = {
      |                                                   ^~
globals.hpp:32:51: error: template argument 5 is invalid
globals.hpp:38:11: error: ‘CTexture’ was not declared in this scope
   38 | inline SP<CTexture> g_pTexture = nullptr;
      |           ^~~~~~~~
globals.hpp:38:19: error: template argument 1 is invalid
   38 | inline SP<CTexture> g_pTexture = nullptr;
      |                   ^
globals.hpp:38:34: error: cannot convert ‘std::nullptr_t’ to ‘int’ in initialization
   38 | inline SP<CTexture> g_pTexture = nullptr;
      |                                  ^~~~~~~
main.cpp: In function ‘void loadTexture(std::filesystem::__cxx11::path, bool)’:
main.cpp:22:18: error: cannot convert ‘std::nullptr_t’ to ‘int’ in assignment
   22 |     g_pTexture = nullptr;
      |                  ^~~~~~~
main.cpp:23:29: error: ‘CTexture’ was not declared in this scope; did you mean ‘g_pTexture’?
   23 |     g_pTexture = makeShared<CTexture>();
      |                             ^~~~~~~~
      |                             g_pTexture
main.cpp:23:38: error: no matching function for call to ‘makeShared<<expression error> >()’
   23 |     g_pTexture = makeShared<CTexture>();
      |                  ~~~~~~~~~~~~~~~~~~~~^~
  • there is 1 candidate
In file included from /usr/include/hyprutils/signal/Signal.hpp:10,
                 from /usr/include/hyprland/src/helpers/signal/Signal.hpp:3,
                 from /usr/include/hyprland/src/devices/IHID.hpp:6,
                 from /usr/include/hyprland/src/devices/IKeyboard.hpp:3,
                 from /usr/include/hyprland/src/devices/Keyboard.hpp:3,
                 from CDotDecoration.hpp:2:
    • candidate 1: ‘template<class U, class ... Args> Hyprutils::Memory::CSharedPointer<T> Hyprutils::Memory::makeShared(Args&& ...)’
      /usr/include/hyprutils/memory/SharedPtr.hpp:196:48:
        196 |         [[nodiscard]] inline CSharedPointer<U> makeShared(Args&&... args) {
            |                                                ^~~~~~~~~~
      • template argument deduction/substitution failed:
        • error: template argument 1 is invalid
          main.cpp:23:38:
             23 |     g_pTexture = makeShared<CTexture>();
                |                  ~~~~~~~~~~~~~~~~~~~~^~
main.cpp:24:15: error: base operand of ‘->’ is not a pointer
   24 |     g_pTexture->allocate();
      |               ^~
main.cpp:36:15: error: base operand of ‘->’ is not a pointer
   36 |     g_pTexture->m_size = textureSize;
      |               ^~
main.cpp:39:44: error: base operand of ‘->’ is not a pointer
   39 |     glBindTexture(GL_TEXTURE_2D, g_pTexture->m_texID);
      |                                            ^~
main.cpp:53:23: error: ‘g_pTextures’ was not declared in this scope; did you mean ‘g_pTexture’?
   53 |     for (auto &pair : g_pTextures) {
      |                       ^~~~~~~~~~~
      |                       g_pTexture
main.cpp:56:32: error: ‘CTexture’ was not declared in this scope; did you mean ‘g_pTexture’?
   56 |       pair.second = makeShared<CTexture>();
      |                                ^~~~~~~~
      |                                g_pTexture
main.cpp:56:41: error: no matching function for call to ‘makeShared<<expression error> >()’
   56 |       pair.second = makeShared<CTexture>();
      |                     ~~~~~~~~~~~~~~~~~~~~^~
  • there is 1 candidate
    • candidate 1: ‘template<class U, class ... Args> Hyprutils::Memory::CSharedPointer<T> Hyprutils::Memory::makeShared(Args&& ...)’
      /usr/include/hyprutils/memory/SharedPtr.hpp:196:48:
        196 |         [[nodiscard]] inline CSharedPointer<U> makeShared(Args&&... args) {
            |                                                ^~~~~~~~~~
      • template argument deduction/substitution failed:
        • error: template argument 1 is invalid
          main.cpp:56:41:
             56 |       pair.second = makeShared<CTexture>();
                |                     ~~~~~~~~~~~~~~~~~~~~^~
main.cpp: In function ‘void initialLoad()’:
main.cpp:92:60: warning: ‘Hyprlang::CConfigValue* HyprlandAPI::getConfigValue(void*, const std::string&)’ is deprecated [-Wdeprecated-declarations]
   92 |       (const Hyprlang::STRING *)HyprlandAPI::getConfigValue(
      |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
   93 |           PHANDLE, "plugin:hyprfoci:imgs")
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                  
In file included from globals.hpp:3:
/usr/include/hyprland/src/plugins/PluginAPI.hpp:162:52: note: declared here
  162 |     APICALL [[deprecated]] Hyprlang::CConfigValue* getConfigValue(HANDLE handle, const std::string& name);
      |                                                    ^~~~~~~~~~~~~~
main.cpp:96:60: warning: ‘Hyprlang::CConfigValue* HyprlandAPI::getConfigValue(void*, const std::string&)’ is deprecated [-Wdeprecated-declarations]
   96 |       (const Hyprlang::STRING *)HyprlandAPI::getConfigValue(
      |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
   97 |           PHANDLE, "plugin:hyprfoci:img")
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                   
/usr/include/hyprland/src/plugins/PluginAPI.hpp:162:52: note: declared here
  162 |     APICALL [[deprecated]] Hyprlang::CConfigValue* getConfigValue(HANDLE handle, const std::string& name);
      |                                                    ^~~~~~~~~~~~~~
main.cpp:102:18: error: cannot convert ‘std::nullptr_t’ to ‘int’ in assignment
  102 |     g_pTexture = nullptr;
      |                  ^~~~~~~
main.cpp:106:20: error: ‘g_pTextures’ was not declared in this scope; did you mean ‘g_pTexture’?
  106 |     for (auto &t : g_pTextures) {
      |                    ^~~~~~~~~~~
      |                    g_pTexture
main.cpp:112:20: error: ‘g_pTextures’ was not declared in this scope; did you mean ‘g_pTexture’?
  112 |     for (auto &t : g_pTextures) {
      |                    ^~~~~~~~~~~
      |                    g_pTexture
main.cpp:115:18: error: cannot convert ‘std::nullptr_t’ to ‘int’ in assignment
  115 |     g_pTexture = nullptr;
      |                  ^~~~~~~
main.cpp: In function ‘void onConfigReload(void*, std::any)’:
main.cpp:148:39: error: ‘class CCompositor’ has no member named ‘m_lastWindow’
  148 |   const auto PWINDOW = g_pCompositor->m_lastWindow.lock();
      |                                       ^~~~~~~~~~~~
main.cpp: In function ‘PLUGIN_DESCRIPTION_INFO pluginInit(void*)’:
main.cpp:179:30: warning: ‘bool HyprlandAPI::addConfigValue(void*, const std::string&, const Hyprlang::CConfigValue&)’ is deprecated [-Wdeprecated-declarations]
  179 |   HyprlandAPI::addConfigValue(PHANDLE, "plugin:hyprfoci:size",
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  180 |                               Hyprlang::VEC2{20, 20});
      |                               ~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/hyprland/src/plugins/PluginAPI.hpp:140:33: note: declared here
  140 |     APICALL [[deprecated]] bool addConfigValue(HANDLE handle, const std::string& name, const Hyprlang::CConfigValue& value);
      |                                 ^~~~~~~~~~~~~~
main.cpp:181:30: warning: ‘bool HyprlandAPI::addConfigValue(void*, const std::string&, const Hyprlang::CConfigValue&)’ is deprecated [-Wdeprecated-declarations]
  181 |   HyprlandAPI::addConfigValue(PHANDLE, "plugin:hyprfoci:pos",
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  182 |                               Hyprlang::VEC2{10, 10});
      |                               ~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/hyprland/src/plugins/PluginAPI.hpp:140:33: note: declared here
  140 |     APICALL [[deprecated]] bool addConfigValue(HANDLE handle, const std::string& name, const Hyprlang::CConfigValue& value);
      |                                 ^~~~~~~~~~~~~~
main.cpp:183:30: warning: ‘bool HyprlandAPI::addConfigValue(void*, const std::string&, const Hyprlang::CConfigValue&)’ is deprecated [-Wdeprecated-declarations]
  183 |   HyprlandAPI::addConfigValue(PHANDLE, "plugin:hyprfoci:origin",
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  184 |                               Hyprlang::VEC2{0, 0});
      |                               ~~~~~~~~~~~~~~~~~~~~~
/usr/include/hyprland/src/plugins/PluginAPI.hpp:140:33: note: declared here
  140 |     APICALL [[deprecated]] bool addConfigValue(HANDLE handle, const std::string& name, const Hyprlang::CConfigValue& value);
      |                                 ^~~~~~~~~~~~~~
main.cpp:187:22: error: ‘configStringToInt’ was not declared in this scope
  187 |       Hyprlang::INT{*configStringToInt("rgba(11ff3388)")});
      |                      ^~~~~~~~~~~~~~~~~
main.cpp:188:30: warning: ‘bool HyprlandAPI::addConfigValue(void*, const std::string&, const Hyprlang::CConfigValue&)’ is deprecated [-Wdeprecated-declarations]
  188 |   HyprlandAPI::addConfigValue(PHANDLE, "plugin:hyprfoci:rounding",
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  189 |                               Hyprlang::FLOAT{4.0});
      |                               ~~~~~~~~~~~~~~~~~~~~~
/usr/include/hyprland/src/plugins/PluginAPI.hpp:140:33: note: declared here
  140 |     APICALL [[deprecated]] bool addConfigValue(HANDLE handle, const std::string& name, const Hyprlang::CConfigValue& value);
      |                                 ^~~~~~~~~~~~~~
main.cpp:191:30: warning: ‘bool HyprlandAPI::addConfigValue(void*, const std::string&, const Hyprlang::CConfigValue&)’ is deprecated [-Wdeprecated-declarations]
  191 |   HyprlandAPI::addConfigValue(PHANDLE, "plugin:hyprfoci:img",
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  192 |                               Hyprlang::STRING{"none"});
      |                               ~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/hyprland/src/plugins/PluginAPI.hpp:140:33: note: declared here
  140 |     APICALL [[deprecated]] bool addConfigValue(HANDLE handle, const std::string& name, const Hyprlang::CConfigValue& value);
      |                                 ^~~~~~~~~~~~~~
main.cpp:193:30: warning: ‘bool HyprlandAPI::addConfigValue(void*, const std::string&, const Hyprlang::CConfigValue&)’ is deprecated [-Wdeprecated-declarations]
  193 |   HyprlandAPI::addConfigValue(PHANDLE, "plugin:hyprfoci:imgs",
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  194 |                               Hyprlang::STRING{"none"});
      |                               ~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/hyprland/src/plugins/PluginAPI.hpp:140:33: note: declared here
  140 |     APICALL [[deprecated]] bool addConfigValue(HANDLE handle, const std::string& name, const Hyprlang::CConfigValue& value);
      |                                 ^~~~~~~~~~~~~~
main.cpp:198:23: error: ‘SCallbackInfo’ has not been declared; did you mean ‘SCallstackFrameInfo’?
  198 |       [&](void *self, SCallbackInfo &info, std::any data) {
      |                       ^~~~~~~~~~~~~
      |                       SCallstackFrameInfo
main.cpp:196:55: warning: ‘SP<Hypr_dummyClass> HyprlandAPI::registerCallbackDynamic(void*, const std::string&, HOOK_CALLBACK_FN)’ is deprecated [-Wdeprecated-declarations]
  196 |   static auto P = HyprlandAPI::registerCallbackDynamic(
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
  197 |       PHANDLE, "closeWindow",
      |       ~~~~~~~~~~~~~~~~~~~~~~~                          
  198 |       [&](void *self, SCallbackInfo &info, std::any data) {
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  199 |         onCloseWindow(self, data);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~                     
  200 |       });
      |       ~~                                               
/usr/include/hyprland/src/plugins/PluginAPI.hpp:174:63: note: declared here
  174 |     APICALL [[deprecated]] [[nodiscard]] SP<HOOK_CALLBACK_FN> registerCallbackDynamic(HANDLE handle, const std::string& event, HOOK_CALLBACK_FN fn);
      |                                                               ^~~~~~~~~~~~~~~~~~~~~~~
main.cpp:198:7: error: could not convert ‘<lambda closure object>pluginInit(void*)::<lambda(void*, int&, std::any)>()’ from ‘pluginInit(void*)::<lambda(void*, int&, std::any)>’ to ‘HOOK_CALLBACK_FN’ {aka ‘Hypr_dummyClass’}
  198 |       [&](void *self, SCallbackInfo &info, std::any data) {
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |       |
      |       pluginInit(void*)::<lambda(void*, int&, std::any)>
  199 |         onCloseWindow(self, data);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~
  200 |       });
      |       ~
main.cpp:204:23: error: ‘SCallbackInfo’ has not been declared; did you mean ‘SCallstackFrameInfo’?
  204 |       [&](void *self, SCallbackInfo &info, std::any data) {
      |                       ^~~~~~~~~~~~~
      |                       SCallstackFrameInfo
main.cpp:202:56: warning: ‘SP<Hypr_dummyClass> HyprlandAPI::registerCallbackDynamic(void*, const std::string&, HOOK_CALLBACK_FN)’ is deprecated [-Wdeprecated-declarations]
  202 |   static auto P1 = HyprlandAPI::registerCallbackDynamic(
      |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
  203 |       PHANDLE, "activeWindow",
      |       ~~~~~~~~~~~~~~~~~~~~~~~~                          
  204 |       [&](void *self, SCallbackInfo &info, std::any data) {
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  205 |         onActiveWindow(self, data);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~                     
  206 |       });
      |       ~~                                                
/usr/include/hyprland/src/plugins/PluginAPI.hpp:174:63: note: declared here
  174 |     APICALL [[deprecated]] [[nodiscard]] SP<HOOK_CALLBACK_FN> registerCallbackDynamic(HANDLE handle, const std::string& event, HOOK_CALLBACK_FN fn);
      |                                                               ^~~~~~~~~~~~~~~~~~~~~~~
main.cpp:204:7: error: could not convert ‘<lambda closure object>pluginInit(void*)::<lambda(void*, int&, std::any)>()’ from ‘pluginInit(void*)::<lambda(void*, int&, std::any)>’ to ‘HOOK_CALLBACK_FN’ {aka ‘Hypr_dummyClass’}
  204 |       [&](void *self, SCallbackInfo &info, std::any data) {
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |       |
      |       pluginInit(void*)::<lambda(void*, int&, std::any)>
  205 |         onActiveWindow(self, data);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
  206 |       });
      |       ~
main.cpp:209:23: error: ‘SCallbackInfo’ has not been declared; did you mean ‘SCallstackFrameInfo’?
  209 |       [&](void *self, SCallbackInfo &info, std::any data) {
      |                       ^~~~~~~~~~~~~
      |                       SCallstackFrameInfo
main.cpp:207:56: warning: ‘SP<Hypr_dummyClass> HyprlandAPI::registerCallbackDynamic(void*, const std::string&, HOOK_CALLBACK_FN)’ is deprecated [-Wdeprecated-declarations]
  207 |   static auto P2 = HyprlandAPI::registerCallbackDynamic(
      |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
  208 |       PHANDLE, "configReloaded",
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~                        
  209 |       [&](void *self, SCallbackInfo &info, std::any data) {
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  210 |         onConfigReload(self, data);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~                     
  211 |       });
      |       ~~                                                
/usr/include/hyprland/src/plugins/PluginAPI.hpp:174:63: note: declared here
  174 |     APICALL [[deprecated]] [[nodiscard]] SP<HOOK_CALLBACK_FN> registerCallbackDynamic(HANDLE handle, const std::string& event, HOOK_CALLBACK_FN fn);
      |                                                               ^~~~~~~~~~~~~~~~~~~~~~~
main.cpp:209:7: error: could not convert ‘<lambda closure object>pluginInit(void*)::<lambda(void*, int&, std::any)>()’ from ‘pluginInit(void*)::<lambda(void*, int&, std::any)>’ to ‘HOOK_CALLBACK_FN’ {aka ‘Hypr_dummyClass’}
  209 |       [&](void *self, SCallbackInfo &info, std::any data) {
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |       |
      |       pluginInit(void*)::<lambda(void*, int&, std::any)>
  210 |         onConfigReload(self, data);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
  211 |       });
      |       ~
CDotDecoration.cpp:5:10: fatal error: hyprland/src/desktop/Window.hpp: No such file or directory
    5 | #include <hyprland/src/desktop/Window.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:2: all] Error 1
```
I'm also using omarchy

**Comment by RoundUpSSBM** [comment]
This repo hasn't been maintained since Hyprland 0.52 (despite multiple PRs). you can check out my fork of it [here](https://github.com/roundupssbm/hyprfoci) which is working on 0.55.2
